config/routes.rb
No9527::Application.routes.draw do

  root  'static_pages#home'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',               via: 'get'
  match '/signin',  to: 'sessions#new',            via: 'get'
  match '/signout', to: 'sessions#destroy',        via: 'delete'
  match '/help',    to: 'static_pages#help',       via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name,   presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email,  presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = '邮箱或密码不正确'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "登录成功!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "No9527"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Return the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<!--Navbar-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "No 9527", root_path, id: "logo" %>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "主页", root_path %></li>
        <li><%= link_to "帮助", help_path %></li>
        <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">账户<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "个人资料", current_user %></li>
            <li><%= link_to "设置", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "退出", signout_path, method: "delete" %>
            </li>

          </ul>
        </li>
        <% else %>
        <li> <%= link_to "登录", signin_path %> </li>
        <% end %>
      </ul>
    </div>

  </div>

</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="jumbotron">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="erroe_explanation">
    <div class="alert alert-error">
      有 <%= @user.errors.count %> 处错误导致无法注册
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li>  <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, '帮助') %>
<h1>帮助</h1>
<p>
   高端大气上档次，低调奢华有内涵，
   奔放洋气有深度，简约时尚国际范，
   低端粗俗甩节操，土憋矫情无下限，
   装模作样绿茶婊，外猛内柔女汉子，
   卖萌嘟嘴剪刀手，忧郁深沉无所谓，
   狂拽炫酷吊炸天，冷艳高贵接地气，
   时尚靓丽小清新，可爱乡村非主流，
   贵族王朝杀马特，提莫团战必须死。
</p>

app/views/static_pages/home.html.erb
<% provide(:title, '主页') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h1 class="margin-base-vertical">Have you ever seen the rain?</h1>

    <p>
      <p>
        When it's over, so they say, it'll rain a sunny day. I know,    Shinin down like water.
      </p>

      <p>
        I want to know, have you ever seen the rain?
      </p>

      <form action="/mailing-list" method="post" class="margin-base-vertical">
        <p class="input-group">
          <span class="input-group-addon">@</span>
          <input type="text" class="form-control input-lg" name="email" placeholder="jonsnow@knowsnothi.ng" />
        </p>
        <p class="help-block text-center"><small>We won't send you spam. Unsubscribe at any time.</small></p>
        <p class="text-center">
          <button type="submit" class="btn btn-success btn-lg">Keep me posted</button>
        </p>
      </span>
    </form>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, '注册') %>
<h1>注 册</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f|  %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name%>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "创建帐户", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>